### ISSUE TITLE
nxos_l3_interfaces should configure `no switchport`

### ISSUE THREAD

**Issue by kbreit** [ansible-collections/cisco.nxos#16]
##### SUMMARY
The `nxos_l3_interfaces` module configures layer 3 interfaces. An interface is brought into layer 3 mode by executing the `no switchport` command. However, isn’t obvious `nxos_l3_interfaces` issues that command. If it does, the documentation should state that. Otherwise, the command should be sent to each interface implicitly.

From https://github.com/ansible/ansible/issues/67261

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_l3_interfaces

**Comment by NilashishC** [comment]
cc @cidrblock

**Comment by cidrblock** [comment]
The resource modules were designed to be used in a layered approach.  Setting the `mode` of the interface is not specifically an L3 property, so it is part of the base configuration in the `nxos_interfaces` module.

**Comment by NilashishC** [comment]
Hi @kbreit. As mentioned above, this is based on how the Resource Modules have been designed to work. 

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists to talk about this and we might be persuaded otherwise.

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
