### ISSUE TITLE
Add nxos_vrfs Resource Module

### ISSUE THREAD

**Issue by clammers** [ansible-collections/cisco.nxos#184]
##### SUMMARY

It seems that some nxos modules are just copy&pasted from the old repository without having the new resource model states described here [Resource Models](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html) Like nxos_vrf it just uses the aggregate and purge arguments.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_vrf
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by NilashishC** [comment]
@clammers I'm not sure if I totally understand the issue here. Not all resource specific modules are Resource Modules. If you look at the [README](https://github.com/ansible-collections/cisco.nxos#modules), only the modules with short description ending with "resource module" are Resource Modules. Having said that, we're in the process of deprecating and replacing the old modules with corresponding Resource Modules.

**Comment by clammers** [comment]
Yes, thats the point. How is the progress for the nxos_vrf module to be "resource module" capable?

**Comment by NilashishC** [comment]
@clammers a vrf resource module is not in our immediate roadmap but we do plan to add it in the future. If you wish you can make this a feature request for the same.

**Comment by Ruchip16** [comment]
closing this issue as nxos_vrf_global module is merged. Ref #870
