### ISSUE TITLE
Support for NXOS without the "feature privilege" enabled

### ISSUE THREAD

**Issue by lordofire** [ansible-collections/cisco.nxos#304]
Hi there,

Recently we have got some information that Cisco NXOS 10.1+ version will not support "feature privilege" anymore. I think currently this is the a pretty fundamental logic in cisco.nxos ansible module when using `network_cli`(have not tested nxapi, but felt should be similar) to deploy and manage the config. Is there anyway we could get rid of this dependencies for this cisco.nxos ansible module? If not, is there any other recommended approach for this from the long term support perspective?

Thanks

**Comment by lordofire** [comment]
Hi, any update on this topic?

**Comment by NilashishC** [comment]
Hi @lordofire. Thank you for your interest in Ansible!

The code that depends on `feature privilege` or `show privilege` output is triggered only when privilege escalation (`become: True`) is enabled. From the discussions we have had with Cisco, I believe the recommended approach is now to use RBACL instead of IOS type "enable" privilege escalation which got dropped starting from NX-OS 10.x releases. Hence, this should have no impact on existing Ansible playbooks if privilege escalation is disabled and `ansible_user` has enough privileges to run commands.

As for NX-API (or `ansible_connection: httpapi`), `enable` privilege escalation never had any impact because of the way the request-response works and if `become: True`, we throw a [warning message](https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/httpapi/nxos.py#L89-L93) about the same. On receiving a request with `enable` command, the device just returns back a success message and we have no way to feed in the enable password. For example, here's the same thing done via NX-API sandbox on a N9Kv running NX-OS 7.0(3)I5(1):

Message Format: `json`
Command type: `cli_show_ascii`

Request:
```
{
  "ins_api": {
    "version": "1.0",
    "type": "cli_show_ascii",
    "chunk": "0",
    "sid": "1",
    "input": "enable",
    "output_format": "json"
  }
}
```
Response:
```
{
  "ins_api": {
    "sid": "eoc",
    "type": "cli_show_ascii",
    "version": "1.0",
    "outputs": {
      "output": {
        "code": "200",
        "msg": "Success",
        "input": "enable",
        "body": {}
      }
    }
  }
}
```

Please let me know if you have questions on this. I'm happy to discuss this further!

**Comment by NilashishC** [comment]
@lordofire Since, we haven't heard from you yet, I'm assuming the previous response answered your question. As such, I'll be closing this ticket. If you have further questions, please feel free to reach out to us through either of the following channels:
- IRC: #ansible-network on irc.libera.chat <https://libera.chat/>_
- Slack - https://ansiblenetwork.slack.com
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you!
