### ISSUE TITLE
Check mode does not work for non-existent subinterfaces with several nxos modules

### ISSUE THREAD

**Issue by zendritic** [ansible-collections/cisco.nxos#376]
##### SUMMARY

When running a task in check mode using nxos_vrf_interface and nxos_l3_interfaces, task ends in MODULE FAILURE. The module is issuing the command "show interface Ethernetx/x.x". The device responds "Invalid Range at '^' marker", which the module is presumably parsing as std err. This output is expected if the subinterface doesn't exist.  
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_vrf_interface
nxos_l3_interfaces
##### ANSIBLE VERSION

```paste below
Difficult to copy and paste large amounts of text in our environment but we are on 4.7.0.
```

##### COLLECTION VERSION

```paste below
Whatever is included in 4.7.0 community.
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AWX Execution environment container 0.2.0 with community 4.7.0 installed.

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Check mode should show commands that create the subinterface.

##### ACTUAL RESULTS

MODULE FAILURE with python trace.

```paste below

```

**Comment by NilashishC** [comment]
Hello @zendritic. The `"Invalid Range at '^' marker"` message triggers the terminal standard error regex defined [here](https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/terminal/nxos.py#L53). Removing this regular expression would result in other unexpected issues.

As a workaround for your particular scenario, you can override the terminal regexes by specifying it in the [ansible_terminal_stderr_re](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/network_cli_connection.html#parameter-terminal_stderr_re) var in your task. Please note that since this overrides the existing list, you would have to specify all the existing regexes exluding the one mentioned above.

On a side note, it seems you are still using `nxos_l3_interface`, this module has been deprecated quite some time back and will soon be removed. Please switch to the newer [nxos_l3_interfaces](https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_l3_interfaces_module.html) resource module which doesn't have this issue.

As such, I'll be closing this ticket. Please feel free to re-open this or reach out to us at any of the modes mentioned here https://docs.ansible.com/ansible/latest/community/communication.html. Thank you for your interest in Ansible!
