### ISSUE TITLE
ansible.netcommon 3.0.0 causes an issue #145

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/cisco.nxos#505]
##### SUMMARY

The default value of `ssh_type` option has been changed since ansible.netcommon 3.0.0, it causes an issue #145.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible.netcommon 3.0.0  
ansible.utils     2.6.1  
cisco.nxos        2.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 8.5
Ansible Automation Platform 2.1.0
EE image : registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest

##### STEPS TO REPRODUCE

I didn't get the customer's playbook, but it uses the `nxos_vlans` module

##### ACTUAL RESULTS

It hits the error as discussed in the below issue:
https://github.com/ansible-collections/cisco.nxos/issues/145#issuecomment-731404727

Here is a fragment of the output from my customer:
```
The full traceback is:
  File "/runner/requirements_collections/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 133, in get_network_resources_facts
    inst.populate_facts(
  File "/runner/requirements_collections/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/vlans/vlans.py", line 75, in populate_facts
    structured = self.get_device_data(connection, "show vlan | json")
  File "/runner/requirements_collections/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/vlans/vlans.py", line 55, in get_device_data
    return connection.get(show_cmd)
  File "/usr/lib/python3.8/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
```

It repaired to set a variable `ansible_network_cli_ssh_type: paramiko`.  Also we confirmed it worked when we used with ansible.netcommon 2.6.1.

Can you please notice the incompatibility and recommend to set the above variable until the issue will be fixed in the pylibssh?

https://github.com/ansible/pylibssh/issues/208

**Comment by NilashishC** [comment]
@sugitk Thank you for reporting this. The actual issue here is with ansible-pylibssh and documented in https://github.com/ansible/pylibssh/issues/208. As you have already mentioned, explicitly setting `ansible_network_cli_ssh_type: paramiko` would fix this issue. However, a workaround was added to get past this by trying `show vlan | json-pretty` first which doesn't have this issue with libssh. Can we know which NX-OS version (and Nexus chassis) is being used? Is the `| json-pretty` filter not supported on it?

Ref: https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/module_utils/network/nxos/facts/vlans/vlans.py#L71-L84

**Comment by feisa** [comment]
It would be 18 different tickets, ansible_network_cli_ssh_type: paramiko fixes the issue. Ill wait until this case is resolved until proceeding with other cases

**Comment by sugitk** [comment]
@NilashishC Good morning,
I am sorry I didn't get the version number of NX-OS from my customer..

**Comment by NilashishC** [comment]
@sugitk For NX-OS versions that do not support `| json-pretty`, `ansible_network_cli_ssh_type: paramiko` has to be set unfortunately. Since this is an issue with ansible-pylibssh and not cisco.nxos, I'll be closing this ticket and tracking this in https://github.com/ansible/pylibssh/issues/208 which is already being looked into.
