### ISSUE TITLE
The module nxos_command was redirected to cisco.nxos.nxos_command, which could not be loaded.

### ISSUE THREAD

**Issue by sathuish** [ansible-collections/cisco.nxos#581]
To connect with Cisco devices, we use the Python Ansible module. Please find below the syntax. Can you confirm whether the error originates at the source or at the destination? Is there any Cisco module that needs to be installed with the existing Python at source?

root@centos-765bcdf6fd-c67sx /]# Python/bin/python Python/bin/ansible all -i xx.xx.x.xx, -c local -u "admin" -m nxos_command -a "commands='show running-config leaf 2111 interface ethernet 1/3'"
xx.xx.x.xx | FAILED! => {
   "msg": "The module nxos_command was redirected to cisco.nxos.nxos_command, which could not be loaded."
}

**Comment by NilashishC** [comment]
@sathuish To debug this further we would need some more information.

- Which ansible-core version are you running?
- Which python version are you running?
- How is the cisco.nxos collection installed (via Galaxy or from source)?
- What does your playbook look like?


Also FYI, filling the issue template while raising a bug report is a good idea since it relays the above information to the maintainers before hand.

**Comment by sathuish** [comment]
@NilashishC Thank you for your feedback. The issue was that the cisco-nxos collection was missing.
**Another question:** Can the collections be installed on a custom path? The collections are installed by 
default in the /.ansbile folder. Because our application is container-based, all microservices will be created in separate containers, and because we are using standalone Python, the Python path will be mounted on all pods for the application to use. We have ansible installed in our standalone Python. We must install the collection in a commonplace so that we can mount that commonplace for ansible to use.

**Comment by NilashishC** [comment]
Hello @sathuish. Glad your cisco.nxos related issue is resolved.

You can use `ANSIBLE_COLLECTIONS_PATH` variable to override how the lookup occurs. However, I don't know if this would correctly work in the setup you mentioned. This needs more insights from the Ansible Core team. Please share your query in the Ansible Project Mailing List (https://groups.google.com/g/ansible-project) for further help on this.

Since the cisco.nxos issue has been resolved, I'm closing this ticket. Thank you!
