### ISSUE TITLE
Unable to install the collection to offline environment

### ISSUE THREAD

**Issue by tevehmas** [ansible-collections/cisco.nxos#780]
##### SUMMARY
Unable to install the cisco.nxos collection to offline environment.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.4]
```

##### OS / ENVIRONMENT

CentOS 8 (4.18.0-305.17.1.el8_4.x86_64)

##### STEPS TO REPRODUCE

1. Download cisco-nxos-5.2.1.tar.gz package from Ansible Galaxy site
2. Move the tar.gz file to offline Ansible Control machine
3. Install cisco-nxos collection: ansible-galaxy collection install cisco-nxos-5.2.1.tar.gz

##### EXPECTED RESULTS

Ansible-Galaxy collection cisco.nxos installed succesfully.

##### ACTUAL RESULTS

```paste below
Starting galaxy collection install process
Process install dependency map
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -2] Name or service not known>

```

**Comment by NilashishC** [comment]
@tevehmas Do you have ansible.netcommon and ansible.utils installed in the air-gapped machine? The `cisco.nxos` collection requires these two, which is likely why ansible-galaxy fails trying to pull them from galaxy.ansible.com.

Please install the aforementioned collections first and then try installing cisco.nxos. If that doesn't solve this issue, please open a ticket in https://github.com/ansible/ansible since it would be a ansible-galaxy CLI client issue then. Thank you!
