### ISSUE TITLE
Vlan_group module for cisco ucs not properly available, no proper playbook available for creating new vlan group and adding vlan to vlan group

### ISSUE THREAD

**Issue by vivekanand552** [ansible-collections/cisco.nxos#80]
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
<cisco ucs vlan_group>

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
```

**Comment by NilashishC** [comment]
Hi @vivekanand552!

Thanks very much for your interest in Ansible. It sincerely means a lot to us. 

This appears to be something that should be filed against another project, and let us explain our reasons for thinking this:

   * The issue title refers to the unavailability of proper resources for Cisco UCS module to configure VLAN groups. Since this collection is exclusively for Ansible Cisco NX-OS modules, we would suggest you to open a ticket in the Cisco UCS collection repo (https://github.com/CiscoDevNet/ansible-ucs).

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
