### ISSUE TITLE
Trying to execute the nxos command. It throws an error saying unexpected error during module execution

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.nxos#93]
_From @sharvesh06 on Apr 30, 2020 17:17_

---
name: 🐛 Bug report
---

##### SUMMARY
Trying to execute the nxos command. It throws an error saying unexpected error during module execution

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos
nxos_command
cisco routers
ansible

##### ANSIBLE VERSION

```paste below
ansible version 2.9.7
python version = 2.7.12
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
---
- name: pinging the switch
  hosts: all
  connection: local
  tasks:
    - name: show version
      nxos_command:
        commands: show version
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/nxos.py", line 137, in run
    out = conn.get_prompt()
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ConnectionError: command timeout triggered, timeout value is 10 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
fatal: [172.18.15.10]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

_Copied from original issue: ansible/ansible#69263_

**Comment by Akasurde** [comment]
cc @sharvesh06

**Comment by NilashishC** [comment]
@sharvesh60 Did you try bumping up the `command_timeout` value as mentioned in the traceback and see if that fixes it? In case you still hit the same issue, please run the task with `ansible_persistent_log_messages` enabled and share the log with us, so that we can debug further. Information on how to enable persistent logging can be found [here](https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#enabling-networking-device-interaction-logging).

**Comment by NilashishC** [comment]
@sharvesh06 Since we haven't received any updates from your end in more than 60 days, we're assuming that this issue is already resolved. As such, we'll be closing this ticket. Please feel free to reopen it in case the issue still persists. You can also reach out to us at #ansible-network on Freenode IRC or through the ANSIBLE-PROJECT mailing list. Thank you!
